name: CI
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 'Enable debug logging'
        default: false
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  GO_VERSION: '1.27'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git log --oneline -3
      - run: echo "Hello from GitHub Actions"
      - run: echo "Go version:$GO_VERSION"
      - run: echo "debug flag = ${{ inputs.debug }}"