name: CI
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 'Enable debug logging'
        default: false
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go run github.com/swaggo/swag/cmd/swag@v1.16.6 init -g cmd/server/main.go --parseInternal --parseDependency
      - run: go build ./...