name: Deploy Reusable

on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        required: true

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
              cd /opt/url-shortener
              docker pull ghcr.io/${{ github.repository }}:${{ inputs.image-tag }}
              docker rm -f url-shortener || true
              docker run -d --name url-shortener -p 80:8080 -e REDIS_ADDR=redis:6379 --network url-shortener ghcr.io/erfangho/url-shortener:${{ inputs.image-tag }}